/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.20.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _1 from "./Cw3FixedMultisig.types";
import * as _2 from "./Cw3FixedMultisig.client";
export namespace contracts {
  export const Cw3FixedMultisig = {
    ..._1,
    ..._2
  };
}
export * from "./types";