/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.20.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./Cw20Ics20.types";
import * as _1 from "./Cw20Ics20.client";
import * as _3 from "./OraiswapConverter.types";
import * as _4 from "./OraiswapConverter.client";
import * as _6 from "./OraiswapFactory.types";
import * as _7 from "./OraiswapFactory.client";
import * as _9 from "./OraiswapIbc.types";
import * as _10 from "./OraiswapIbc.client";
import * as _12 from "./OraiswapLimitOrder.types";
import * as _13 from "./OraiswapLimitOrder.client";
import * as _15 from "./OraiswapOracle.types";
import * as _16 from "./OraiswapOracle.client";
import * as _18 from "./OraiswapPair.types";
import * as _19 from "./OraiswapPair.client";
import * as _21 from "./OraiswapRewarder.types";
import * as _22 from "./OraiswapRewarder.client";
import * as _24 from "./OraiswapRouter.types";
import * as _25 from "./OraiswapRouter.client";
import * as _27 from "./OraiswapStaking.types";
import * as _28 from "./OraiswapStaking.client";
import * as _30 from "./OraiswapToken.types";
import * as _31 from "./OraiswapToken.client";
import * as _33 from './Multicall.types';
import * as _34 from './Multicall.client';
export namespace contracts {
  export const Cw20Ics20 = {
    ..._0,
    ..._1,
  };
  export const OraiswapConverter = {
    ..._3,
    ..._4,
  };
  export const OraiswapFactory = {
    ..._6,
    ..._7,
  };
  export const OraiswapIbc = {
    ..._9,
    ..._10,
  };
  export const OraiswapLimitOrder = {
    ..._12,
    ..._13,
  };
  export const OraiswapOracle = {
    ..._15,
    ..._16,
  };
  export const OraiswapPair = {
    ..._18,
    ..._19,
  };
  export const OraiswapRewarder = {
    ..._21,
    ..._22,
  };
  export const OraiswapRouter = {
    ..._24,
    ..._25,
  };
  export const OraiswapStaking = {
    ..._27,
    ..._28,
  };
  export const OraiswapToken = {
    ..._30,
    ..._31,
  };
  export const Multicall = { ..._33, ..._34 };
}
export * from "./types";